name: AWS CDK Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub Event - ${{ github.event_name }}"
      - run: echo "Runner OS - ${{ runner.os }}"
      - run: echo "Gut Repo - ${{ github.repository }}."
      - uses: actions/checkout@v3
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "23"
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
          cdk --version
          pip show aws-cdk-lib
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-2"
      - name: CDK DIFF
        run: cdk diff
      - name: Deploy to AWS
        run: cdk deploy --app="python3 ${PWD}/app.py" --require-approval=never
 #     - name: Destroy stack
 #       run: cdk destroy --app="python3 ${PWD}/cdk/my_service/app.py" --force